apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-dev
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/smburabari/platform-gitops.git
    targetRevision: main
    path: apps/dev/metrics-server
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # kube-system already exists; ArgoCD must NOT try to create it
      - CreateNamespace=false
