apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - base/

patches:
  - path: base/sa-patch.yaml
    target:
      kind: ServiceAccount
      name: external-dns
