apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: karpenter

resources:
  - https://raw.githubusercontent.com/aws/karpenter/release-0.35.1/karpenter.yaml


patches:
  - target:
      kind: ServiceAccount
      name: karpenter
    patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: karpenter
        namespace: karpenter
        annotations:
          eks.amazonaws.com/role-arn: "<karpenter-irsa-role-arn>"
